services:
  - type: web
    name: security-scanner-v6
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir 백신 app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
